### ISSUE TITLE
Change in phoenix-shared-interface: Every usage of `bool` now aliases to `int`

### ISSUE THREAD

**Issue by lmichaelis** [GothicKit/phoenix-csharp-interface#26]
This change has been made in `phoenix-shared-interface` for improved compatibility with C and other language's C-interop facilities. Relevant commit is https://github.com/GothicKit/phoenix-shared-interface/commit/60b5affc524f9ad39b38d4df0eb453ba578deb28. Adjecent commit changing usages of raw `bool` to `PxBool` is https://github.com/GothicKit/phoenix-shared-interface/commit/b2af7fc7bf1be0f7ff2e23485f8c4a061ada94be.

**Comment by JaXt0r** [comment]
Thanks for the reminder. Implementation changed with: https://github.com/GothicKit/phoenix-csharp-interface/pull/27

Basically we could remove ```[MarshalAs(UnmanagedType.U1)]``` as the default of PInvoke for bool is 4byte anyways. 👍
